package com.platform.challenge.web;
import com.platform.challenge.service.ChallengeService; import com.platform.identity.entity.PlatformRole; import com.platform.identity.repository.AccountRepository; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import java.time.Instant; import java.util.*;
@RestController @RequestMapping("/api/v1/challenges") public class ChallengeController {
 private final ChallengeService service; private final AccountRepository accounts; public ChallengeController(ChallengeService s,AccountRepository a){service=s;accounts=a;}
 private void staff(UUID id){var a=accounts.findById(id).orElseThrow();if(a.getPlatformRole()!=PlatformRole.TEACHER&&a.getPlatformRole()!=PlatformRole.ADMIN&&a.getPlatformRole()!=PlatformRole.PRINCIPAL)throw new AccessDeniedException("Staff access required");}
 @PostMapping public ChallengeResponse create(@Valid @RequestBody CreateRequest r,@AuthenticationPrincipal UUID id){staff(id);return ChallengeResponse.of(service.create(id,r.activityVersionId(),r.title(),r.description(),r.targetCompletions(),r.startsAt()==null?Instant.now():r.startsAt(),r.endsAt()));}
 @PostMapping("/{challengeId}/classes/{classId}") public LinkResponse assign(@PathVariable UUID challengeId,@PathVariable UUID classId,@AuthenticationPrincipal UUID id){staff(id);return LinkResponse.of(service.assign(id,challengeId,classId));}
 @GetMapping("/classes/{classId}") public List<ChallengeResponse> list(@PathVariable UUID classId,@AuthenticationPrincipal UUID id){staff(id);return service.forClass(id,classId).stream().map(ChallengeResponse::of).toList();}
 public record CreateRequest(@NotNull UUID activityVersionId,@NotBlank String title,String description,@Min(1) int targetCompletions,Instant startsAt,Instant endsAt){}
 public record ChallengeResponse(UUID id,UUID activityVersionId,String title,String description,int targetCompletions,Instant startsAt,Instant endsAt){static ChallengeResponse of(com.platform.challenge.entity.Challenge c){return new ChallengeResponse(c.getId(),c.getActivityVersionId(),c.getTitle(),c.getDescription(),c.getTargetCompletions(),c.getStartsAt(),c.getEndsAt());}}
 public record LinkResponse(UUID id,UUID challengeId,UUID schoolClassId){static LinkResponse of(com.platform.challenge.entity.ChallengeClass x){return new LinkResponse(x.getId(),x.getChallengeId(),x.getSchoolClassId());}}
}
