import { FormEvent, useEffect, useState } from 'react';
import AppShell from '../components/AppShell';
import { api, Lookup } from '../lib/api';
export default function AdminContent(){
 const [subjects,setSubjects]=useState<Lookup[]>([]); const [subjectId,setSubjectId]=useState(''); const [title,setTitle]=useState(''); const [activityVersionId,setActivityVersionId]=useState(''); const [challengeTitle,setChallengeTitle]=useState(''); const [target,setTarget]=useState(1); const [status,setStatus]=useState(''); const [busy,setBusy]=useState(false);
 useEffect(()=>{api.listTeacherSubjects().then(x=>{setSubjects(x);if(x[0])setSubjectId(x[0].id)}).catch(e=>setStatus(e?.message||'Could not load subjects.'));},[]);
 async function lesson(e:FormEvent){e.preventDefault();setBusy(true);setStatus('');try{const x=await api.createAdminLesson(subjectId,title);setTitle('');setStatus(`Platform lesson “${x.title}” created. Continue authoring from the admin content workflow.`);}catch(e:any){setStatus(e?.message||'Could not create platform lesson.')}finally{setBusy(false)}}
 async function challenge(e:FormEvent){e.preventDefault();setBusy(true);setStatus('');try{await api.createAdminChallenge(activityVersionId,challengeTitle,'Platform challenge',target);setChallengeTitle('');setActivityVersionId('');setStatus('Platform challenge created.')}catch(e:any){setStatus(e?.message||'Could not create challenge.')}finally{setBusy(false)}}
 return <AppShell workspace="admin"><div className="page-title"><div><span className="eyebrow">PLATFORM CONTENT</span><h1>Create platform learning.</h1><p>Admin-owned content and challenges stay separate from the teacher workspace.</p></div></div>{status&&<div className="safe-note" style={{marginBottom:20}}>{status}</div>}<div className="dashboard-grid"><section className="auth-card"><h2>New platform lesson</h2><form onSubmit={lesson}><label>Subject<select value={subjectId} onChange={e=>setSubjectId(e.target.value)} required>{subjects.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Lesson title<input value={title} onChange={e=>setTitle(e.target.value)} required placeholder="Addition foundations"/></label><button className="btn primary full" disabled={busy||!subjectId}>Create lesson</button></form></section><section className="auth-card"><h2>Platform challenge</h2><p>Use a published activity version as the learning target.</p><form onSubmit={challenge}><label>Activity version ID<input value={activityVersionId} onChange={e=>setActivityVersionId(e.target.value)} required placeholder="Published activity UUID"/></label><label>Challenge title<input value={challengeTitle} onChange={e=>setChallengeTitle(e.target.value)} required/></label><label>Target completions<input type="number" min="1" value={target} onChange={e=>setTarget(Number(e.target.value))}/></label><button className="btn primary full" disabled={busy}>Create challenge</button></form></section></div></AppShell>
}