package com.platform.challenge.service;
import com.platform.challenge.entity.*; import com.platform.challenge.repository.*; import com.platform.common.entity.PublicationStatus; import com.platform.common.web.ResourceNotFoundException; import com.platform.content.repository.ActivityVersionRepository; import com.platform.learning.entity.ActivityAttemptStatus; import com.platform.learning.repository.ActivityAttemptRepository; import com.platform.school.service.SchoolAccessGuard; import com.platform.school.repository.ClassEnrollmentRepository; import com.platform.school.entity.ClassEnrollmentStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.Instant; import java.util.*;
@Service public class ChallengeService {
 private final ChallengeRepository challenges; private final ChallengeClassRepository links; private final ActivityVersionRepository activities; private final ActivityAttemptRepository attempts; private final SchoolAccessGuard guard; private final ClassEnrollmentRepository classEnrollments;
 public ChallengeService(ChallengeRepository c,ChallengeClassRepository l,ActivityVersionRepository a,ActivityAttemptRepository at,SchoolAccessGuard g,ClassEnrollmentRepository ce){challenges=c;links=l;activities=a;attempts=at;guard=g;classEnrollments=ce;}
 @Transactional public Challenge create(UUID owner,UUID activityVersion,String title,String description,int target,Instant starts,Instant ends){var av=activities.findById(activityVersion).orElseThrow(()->new ResourceNotFoundException("ActivityVersion",activityVersion));if(av.getStatus()!=PublicationStatus.PUBLISHED)throw new IllegalArgumentException("Challenge activity must be published");return challenges.save(Challenge.create(owner,activityVersion,title,description,target,starts,ends));}
 @Transactional public ChallengeClass assign(UUID owner,UUID challengeId,UUID classId){Challenge c=challenges.findById(challengeId).orElseThrow(()->new ResourceNotFoundException("Challenge",challengeId));if(!c.getOwnerAccountId().equals(owner))throw new org.springframework.security.access.AccessDeniedException("Only the challenge owner may assign it");guard.requireClassAccess(owner,classId);return links.findByChallengeIdAndSchoolClassId(challengeId,classId).orElseGet(()->links.save(ChallengeClass.create(challengeId,classId)));}
 @Transactional(readOnly=true) public List<Challenge> forClass(UUID accountId,UUID classId){guard.requireClassAccess(accountId,classId);return links.findBySchoolClassId(classId).stream().map(x->challenges.findById(x.getChallengeId()).orElse(null)).filter(Objects::nonNull).filter(c->c.getStatus().equals("ACTIVE")).toList();}
 @Transactional(readOnly=true) public Progress progress(UUID childId,UUID challengeId){Challenge c=challenges.findById(challengeId).orElseThrow(()->new ResourceNotFoundException("Challenge",challengeId));boolean assigned=classEnrollments.findByChildIdAndStatus(childId,ClassEnrollmentStatus.ACTIVE).stream().anyMatch(e->links.findByChallengeIdAndSchoolClassId(challengeId,e.getSchoolClassId()).isPresent());if(!assigned)throw new org.springframework.security.access.AccessDeniedException("Challenge is not assigned to this child");Instant end=c.getEndsAt()==null?Instant.now():c.getEndsAt();long count=attempts.countByChildIdAndActivityVersionIdAndStatusAndCompletedAtGreaterThanEqualAndCompletedAtLessThanEqual(childId,c.getActivityVersionId(),ActivityAttemptStatus.COMPLETED,c.getStartsAt(),end);return new Progress(c.getId(),Math.min(count,c.getTargetCompletions()),c.getTargetCompletions(),count>=c.getTargetCompletions());}
 public record Progress(UUID challengeId,long completions,int targetCompletions,boolean complete){}
}
